/*
 * Copyright (c) 2009, 2016 Robert Bosch GmbH and its subsidiaries.
 * This program and the accompanying materials are made available under
 * the terms of the Bosch Internal Open Source License v4
 * which accompanies this distribution, and is available at
 * http://bios.intranet.bosch.com/bioslv4.txt
 */
package OslcAccess;

/**
 * Interface for a field in {@link OslcRecordI} that maps to a writeable
 * property of that record on the OSLC interface. A property is writeable, if it
 * is a real field in the OSLC record and not a field generated by other
 * properties.
 *
 * @author gug2wi
 */
public interface OslcWriteableFieldI extends OslcFieldI {

    /**
     * Checks, if the field value was changed since the last call of
     * setOslcValue() or the last call of setOslcWriteSuccessfull(). This method
     * is used to determine, if the field content has to be written to the
     * database.
     *
     * @return true, if the field value was changed and shall be written to the
     * database.<br>
     * false, if the field value is unchanged and/or shall not be written to the
     * database.
     */
    public boolean isOslcWritePending();

    /**
     * Informs the field, that the value returned by the last call to
     * getOslcValue() was successfully written to the OSLC server.
     */
    public void setOslcWriteSuccessfull();

}
