/*
 * Copyright (c) 2009, 2021 Robert Bosch GmbH and its subsidiaries.
 * This program and the accompanying materials are made available under
 * the terms of the Bosch Internal Open Source License v4
 * which accompanies this distribution, and is available at
 * http://bios.intranet.bosch.com/bioslv4.txt
 */
package Monitoring;

import UiSupport.UiThreadChecker;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JFrame;

/**
 * Displays the information of the marker on the GUI.
 *
 * @author gug2wi
 */
public class MarkerDialog extends java.awt.Dialog {

    Marker marker;

    /**
     * Creates new form MarkerDialog
     * @param parentFrame
     * @param marker
     */
    public MarkerDialog(JFrame parentFrame, Marker marker) {
        super(parentFrame, true);
        UiThreadChecker.ensureDispatchThread();
        this.marker = marker;
        initComponents();
        this.setTitle("Marker Description");
        markerTitleText.setText(marker.getTitle());
        problemText.setText(marker.getDescription());
        ruleNameText.setText(marker.getRule().getRuleTitle());
        ruleContentText.setText(marker.getRule().getRuleDescriptionText());
        this.setLocationRelativeTo(parentFrame);
        this.setFocusable(true);
        this.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent ke) {
            }

            @Override
            public void keyPressed(KeyEvent ke) {
                if (ke.getKeyCode() == 27) {
                    closeDialog(null);
                }
            }

            @Override
            public void keyReleased(KeyEvent ke) {
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        markerTitleLabel = new javax.swing.JLabel();
        markerTitleText = new javax.swing.JTextField();
        problemLabel = new javax.swing.JLabel();
        ruleTitleLabel = new javax.swing.JLabel();
        ruleDescriptionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        problemText = new javax.swing.JTextArea();
        ruleNameText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ruleContentText = new javax.swing.JTextArea();

        setAlwaysOnTop(true);
        setLocationRelativeTo(null);
        setMinimumSize(new java.awt.Dimension(300, 230));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        markerTitleLabel.setText("Title");

        markerTitleText.setEditable(false);
        markerTitleText.setText("markerTitleText");

        problemLabel.setText("Problem");

        ruleTitleLabel.setText("Rule Name");

        ruleDescriptionLabel.setText("Rule Content");

        problemText.setEditable(false);
        problemText.setColumns(20);
        problemText.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        problemText.setLineWrap(true);
        problemText.setRows(5);
        problemText.setText(" problemText");
        jScrollPane1.setViewportView(problemText);

        ruleNameText.setEditable(false);
        ruleNameText.setText("ruleNameText");

        ruleContentText.setEditable(false);
        ruleContentText.setColumns(20);
        ruleContentText.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        ruleContentText.setLineWrap(true);
        ruleContentText.setRows(5);
        ruleContentText.setText("ruleContentText");
        jScrollPane2.setViewportView(ruleContentText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(problemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ruleTitleLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(markerTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(ruleDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(markerTitleText, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addComponent(ruleNameText)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {markerTitleLabel, problemLabel, ruleTitleLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markerTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(markerTitleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(problemLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ruleNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(ruleTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ruleDescriptionLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        setSize(new java.awt.Dimension(788, 354));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel markerTitleLabel;
    private javax.swing.JTextField markerTitleText;
    private javax.swing.JLabel problemLabel;
    private javax.swing.JTextArea problemText;
    private javax.swing.JTextArea ruleContentText;
    private javax.swing.JLabel ruleDescriptionLabel;
    private javax.swing.JTextField ruleNameText;
    private javax.swing.JLabel ruleTitleLabel;
    // End of variables declaration//GEN-END:variables
}
